ZSH=$HOME/.oh-my-zsh
ZSH_THEME="ys"

plugins=(git osx)

if [[ -e $ZSH/oh-my-zsh.sh ]]; then
    . $ZSH/oh-my-zsh.sh
fi

if [[ -e $HOME/.aliases ]]; then
    . $HOME/.aliases
fi

if [[ -e $HOME/.prompt.zsh ]]; then
    . $HOME/.prompt.zsh
fi

if [[ -e $HOME/.path ]]; then
    . $HOME/.path
fi


plugins=(git osx)
