ZSH=${HOME}/.oh-my-zsh
ZSH_THEME="ys"

plugins=(git osx)

if [[ -e ${ZSH}/oh-my-zsh.sh ]]; then
    . ${ZSH}/oh-my-zsh.sh
fi

if [[ -e ${HOME}/.aliases ]]; then
    . ${HOME}/.aliases.sh
fi

if [[ -e ${HOME}/.prompt.zsh ]]; then
    . ${HOME}/.prompt.zsh
fi

if [[ -e ${HOME}/.path.sh ]]; then
    . ${HOME}/.path.sh
fi


plugins=(git osx)
