# Bash Aliases

# default rsync flags
alias rsync='command rsync -av --progress --exclude-from='${HOME}'/.rsync-excludes.conf'

# ls aliases
if hash exa 2>/dev/null; then
    alias ls='exa -F'
else
    alias ls='command -p ls -FG'
fi

alias l='ls -1'
alias ll='ls -lah'
alias la='ls -la'

# Get rid of pesky network permissions
alias app-enable='sudo xattr -r -d com.apple.quarantine'

# Display open sockets
alias listsocks='command lsof -i -P'

# Run remote SOCKS proxy daemon
alias socks='ssh -D 9999 -f -C -q -N'

# Set neovim as default
if hash nvim 2>/dev/null; then
    alias vim='nvim'
fi

# Hub is default git
if hash hub 2>/dev/null; then
    alias git='hub'
fi

# Colorize YAML
if hash pygmentize 2>/dev/null; then
    alias highlight='pygmentize -l yaml -f 16m -O style=solarized-dark'
    alias lessy='highlight | less -R'
fi

# default pstree
if hash pstree 2>/dev/null; then
    alias pstree='command pstree -g 2 -w'
fi

# set aliases for kubectx
if hash kubectx 2>/dev/null; then
    alias kctx='kubectx'
    alias kns='kubens'
fi

# arch linux
if [ -r /etc/arch-release ]; then
    # `makepkg`
    alias pkg-build='command makepkg -scr'
    alias pkg-install='command makepkg -scri'

    # `pacman`
    alias pac-get='sudo pacman --sync'
    alias pac-remove='sudo pacman --remove'
    alias pac-update='sudo pacman --sync --refresh --upgrade'
    alias pac-search='sudo pacman --sync --search'
fi

# vi: ft=sh
