#!/usr/bin/env bash

HASH="%C(yellow)%h%C(reset)"
RELATIVE_TIME="%C(green)%ar%C(reset)"
AUTHOR="%C(bold blue)%an%C(reset)"
SUBJECT="%s"

FORMAT="$HASH{$RELATIVE_TIME{$AUTHOR{$SUBJECT"

function pretty_git_log() {
    git log --graph --pretty="tformat:$FORMAT" "$@" |
    column -t -s '{' |
    less -FXRS
}
